### ISSUE TITLE
Backtick sql bug when using filter transformer?

### ISSUE THREAD

**Issue by dallincoons** [studio-net/laravel-graphql#17]
When trying to run a query like `query={users(filter:{id:"1"}){id,name}}` it yields the error in MySql:

``Column not found: 1054 Unknown column 'LOWER(id)' in 'where clause' (SQL: select * from `users` where `LOWER(id)` = 1)"``

shouldn't this be ``LOWER(`id`)``?

**Comment by cmizzi** [comment]
Hi ! Thanks for your feedback. I've implemented a fix (see referenced PR). Can you try the branch and tell me if the patch works for your case ?

**Comment by cmizzi** [comment]
See referenced PR
